export const GameConfig = {
  resolution: {
    width: 1920,
    height: 1080,
  },
  world: {
    tileSize: 128,
    chunkSize: 512,
    useEverRogueTileset: false,
    wrapWorld: true,
    bounds: {
      minX: -9600,
      maxX: 9600,
      minY: -9600,
      maxY: 9600,
    },
    decorationDensity: 0.72,
    decorationDrawPadding: 120,
    edgeFadeSize: 480,
    maxCachedChunks: 256,
  },
  sprites: {
    sourceSize: 182,
  },
  player: {
    defaultSpriteSet: "puzas",
    activeSpriteSet: "puzas",
    spriteSets: {
      puzas: {
        name: "Puzas",
        sheet: "./src/assets/sprites/player/puzas/sheet.png",
        preview: "./src/assets/sprites/player/puzas/down.png",
        frameWidth: 48,
        frameHeight: 72,
        framesPerDirection: 3,
        directionRows: {
          down: 0,
          left: 1,
          right: 2,
          up: 3,
        },
      },
      kiki: {
        name: "Kiki",
        sheet: "./src/assets/sprites/player/kiki/sheet.png",
        preview: "./src/assets/sprites/player/kiki/down.png",
        frameWidth: 48,
        frameHeight: 72,
        framesPerDirection: 3,
        directionRows: {
          down: 0,
          left: 1,
          right: 2,
          up: 3,
        },
      },
    },
    speed: 360,
    maxHealth: 100,
    level: 1,
    xp: 0,
    xpBaseRequirement: 8,
    xpGrowth: 1.22,
    pickupRadius: 32,
    magnetRadius: 180,
    invincibilityDuration: 0.85,
    renderWidth: 96,
    renderHeight: 144,
    collisionRadius: 38,
    bumpDistance: 18,
    bumpTime: 0.12,
    dash: {
      cooldown: 2.5,
      duration: 0.18,
      speed: 920,
      invincibilityExtra: 0.06,
    },
    manualShot: {
      cooldown: 0.25,
      damage: 16,
      speed: 820,
      radius: 12,
      maxDistance: 1300,
    },
  },
  enemies: {
    // Active spawn roster: see src/config/EnemyRoster.md (slime + skeletonCaptain boss only).
    slime: {
      name: "Inkling",
      maxHealth: 28,
      speed: 98,
      damage: 7,
      renderSize: 116,
      collisionRadius: 42,
    },
    zombie: {
      name: "Zombie",
      maxHealth: 34,
      speed: 88,
      damage: 8,
      renderSize: 118,
      collisionRadius: 42,
    },
    brainZombie: {
      name: "Brainwalker",
      maxHealth: 42,
      speed: 92,
      damage: 9,
      renderSize: 118,
      collisionRadius: 42,
    },
    vikingUndead: {
      name: "Draugr",
      maxHealth: 48,
      speed: 94,
      damage: 10,
      renderSize: 118,
      collisionRadius: 42,
    },
    skeletonUndead: {
      name: "Rattling Bones",
      maxHealth: 44,
      speed: 96,
      damage: 9,
      renderSize: 118,
      collisionRadius: 42,
    },
    popstarUndead: {
      name: "Popstar Ghoul",
      maxHealth: 52,
      speed: 98,
      damage: 10,
      renderSize: 118,
      collisionRadius: 42,
    },
    knightUndead: {
      name: "Grave Knight",
      maxHealth: 56,
      speed: 90,
      damage: 11,
      renderSize: 118,
      collisionRadius: 44,
    },
    greenDragon: {
      name: "Green Wyrmling",
      maxHealth: 38,
      speed: 92,
      damage: 8,
      renderSize: 118,
      collisionRadius: 42,
    },
    bat: {
      name: "Gutterwing",
      maxHealth: 16,
      speed: 158,
      damage: 6,
      renderSize: 104,
      collisionRadius: 34,
    },
    brute: {
      name: "Bindgeist",
      maxHealth: 72,
      speed: 78,
      damage: 11,
      renderSize: 132,
      collisionRadius: 48,
    },
    crawler: {
      name: "Scrollmite",
      maxHealth: 24,
      speed: 128,
      damage: 7,
      renderSize: 92,
      collisionRadius: 30,
    },
    elite: {
      name: "Chorus Wraith",
      maxHealth: 96,
      speed: 118,
      damage: 12,
      renderSize: 144,
      collisionRadius: 46,
    },
    boss: {
      name: "Archivore",
      maxHealth: 420,
      speed: 70,
      damage: 18,
      renderSize: 168,
      collisionRadius: 58,
    },
    polarDogBoss: {
      name: "Polar Hound",
      isBoss: true,
      maxHealth: 340,
      speed: 104,
      damage: 15,
      renderSize: 160,
      collisionRadius: 54,
    },
    spottedDogBoss: {
      name: "Golden Hound",
      isBoss: true,
      maxHealth: 300,
      speed: 118,
      damage: 13,
      renderSize: 156,
      collisionRadius: 52,
    },
    reaperBoss: {
      name: "Grim Reaper",
      isBoss: true,
      maxHealth: 420,
      speed: 88,
      damage: 16,
      renderSize: 160,
      collisionRadius: 56,
    },
    skeletonCaptain: {
      name: "Skeleton Captain",
      isBoss: true,
      visualType: "slime",
      maxHealth: 600,
      speed: 60,
      damage: 18,
      renderSize: 209,
      collisionRadius: 56,
    },
    wolfPouncer: {
      name: "Moon Wolf",
      maxHealth: 22,
      speed: 182,
      damage: 8,
      renderSize: 118,
      collisionRadius: 36,
    },
    skeletonArcher: {
      name: "Bone Archer",
      maxHealth: 32,
      speed: 92,
      damage: 9,
      renderSize: 110,
      collisionRadius: 34,
    },
    shieldBrute: {
      name: "Bulwark Guard",
      maxHealth: 92,
      speed: 68,
      damage: 10,
      renderSize: 138,
      collisionRadius: 50,
    },
    goblinRunner: {
      name: "Courtyard Goblin",
      maxHealth: 18,
      speed: 168,
      damage: 5,
      renderSize: 96,
      collisionRadius: 30,
    },
    necromancer: {
      name: "Crypt Caller",
      maxHealth: 56,
      speed: 84,
      damage: 11,
      renderSize: 128,
      collisionRadius: 40,
    },
    fireImp: {
      name: "Ember Imp",
      maxHealth: 24,
      speed: 146,
      damage: 8,
      renderSize: 102,
      collisionRadius: 32,
    },
    iceWraith: {
      name: "Rime Wraith",
      maxHealth: 40,
      speed: 112,
      damage: 9,
      renderSize: 120,
      collisionRadius: 36,
    },
    castleKnight: {
      name: "Archive Knight",
      maxHealth: 68,
      speed: 84,
      damage: 12,
      renderSize: 136,
      collisionRadius: 46,
    },
    hitFlashTime: 0.08,
    knockbackForce: 280,
    knockbackFriction: 8,
  },
  spawn: {
    baseInterval: 1.32,
    padding: 170,
    minSpawnDistance: 190,
    maxEnemies: 110,
    maxEnemyDelay: 0.35,
    warmupDuration: 30,
    warmupIntervalMultiplier: 1.6,
  },
  bosses: {
    // Skeleton Captain only — see src/config/EnemyRoster.md and BossDirector.js
    firstSpawnTime: 120,
    spawnInterval: 120,
    spawnChance: 1,
    healthScalePerSpawn: 0.12,
    announcementDuration: 2.8,
    defeatAnnouncementDuration: 2.4,
    activeType: "skeletonCaptain",
    bonusXpOrbs: 6,
    firstKillGuaranteedChest: true,
  },
  traits: {
    // Run Traits: build-defining upgrades. See src/config/TraitDefinitions.js.
    maxTraits: 4,
    appearWeight: 0.5,
    arcaneOverflowHits: 12,
    arcaneOverflowRadius: 150,
    arcaneOverflowDamage: 14,
  },
  synergies: {
    // Cross-weapon synergies. See src/config/SynergyDefinitions.js.
    appearWeight: 0.75,
  },
  eliteModifiers: {
    // Behavior modifiers for normal enemies. See src/config/EnemyModifiers.js.
    firstSpawnTime: 75,
    baseChance: 0.06,
    chancePerMinute: 0.03,
    maxChance: 0.28,
    xpReward: "green",
    maxModifiedEnemies: 22,
  },
  chests: {
    pickupRadius: 40,
    renderSize: 76,
    bobSpeed: 3.4,
    coinReward: 85,
    healAmount: 50,
    animation: {
      shakeDuration: 0.75,
      burstDuration: 0.4,
      revealDelay: 1.05,
    },
  },
  coins: {
    enemyDropChance: 0.07,
    enemyDropMin: 1,
    enemyDropMax: 3,
    bossDropAmount: 18,
    pickupRadius: 12,
    magnetSpeed: 720,
  },
  metaUpgrades: {
    maxHealthPerLevel: 5,
    damageBonusPerLevel: 0.05,
    moveSpeedBonusPerLevel: 0.03,
    xpBonusPerLevel: 0.05,
    pickupRangeBonusPerLevel: 0.05,
    startingCoinsPerLevel: 10,
  },
  waves: {
    announcementDuration: 2.8,
    scaling: {
      minSpawnInterval: 0.38,
      spawnIntervalDecayPerSecond: 0.0026,
      healthGrowthPerSecond: 0.0075,
      maxHealthMultiplier: 2.2,
      speedGrowthPerSecond: 0.0028,
      maxSpeedMultiplier: 1.38,
      earlyHealthRampDuration: 30,
      earlyHealthMultiplier: 0.84,
      midGameSpawnBoostTime: 60,
      midGameSpawnIntervalMultiplier: 0.9,
      bossDefeatSpawnIntervalReduction: 0.04,
      bossDefeatHealthBonus: 0.08,
    },
  },
  weapons: {
    maxLevel: 8,
    starterWeapon: "arcaneBolt",
    arcaneBolt: {
      id: "arcaneBolt",
      name: "Ink Flick",
      cooldown: 0.58,
      range: 880,
      projectileSpeed: 820,
      projectileDamage: 18,
      projectileRadius: 12,
      projectileMaxDistance: 1300,
      pierce: 0,
      upgrades: [
        { stat: "projectileDamage", amount: 4, label: "Damage +4" },
        { stat: "cooldown", multiplier: 0.9, label: "Cooldown -10%" },
        { stat: "projectileSpeed", amount: 80, label: "Projectile speed +80" },
        { stat: "pierce", amount: 1, label: "Pierce +1" },
        { stat: "projectileDamage", amount: 6, label: "Damage +6" },
        { stat: "cooldown", multiplier: 0.88, label: "Cooldown -12%" },
        { stat: "projectileDamage", amount: 8, label: "Damage +8" },
      ],
    },
    orbitingBlade: {
      id: "orbitingBlade",
      name: "Margin Ring",
      cooldown: 0,
      bladeCount: 1,
      damage: 10,
      radius: 108,
      bladeRadius: 20,
      orbitSpeed: 2.1,
      hitCooldown: 0.45,
      upgrades: [
        { stat: "bladeCount", amount: 1, label: "Blade count +1" },
        { stat: "damage", amount: 3, label: "Damage +3" },
        { stat: "orbitSpeed", amount: 0.3, label: "Orbit speed +0.3" },
        { stat: "bladeRadius", amount: 4, label: "Blade size +4" },
        { stat: "damage", amount: 3, label: "Damage +3" },
        { stat: "bladeCount", amount: 1, label: "Blade count +1" },
        { stat: "radius", amount: 16, label: "Orbit radius +16" },
      ],
    },
    holyPulse: {
      id: "holyPulse",
      name: "Lantern Pulse",
      cooldown: 3.8,
      radius: 190,
      damage: 18,
      pulseLife: 0.34,
      upgrades: [
        { stat: "radius", amount: 30, label: "Radius +30" },
        { stat: "damage", amount: 5, label: "Damage +5" },
        { stat: "cooldown", multiplier: 0.9, label: "Cooldown -10%" },
        { stat: "radius", amount: 35, label: "Radius +35" },
        { stat: "damage", amount: 7, label: "Damage +7" },
        { stat: "cooldown", multiplier: 0.88, label: "Cooldown -12%" },
        { stat: "damage", amount: 9, label: "Damage +9" },
      ],
    },
    lightningMark: {
      id: "lightningMark",
      name: "Quill Arc",
      cooldown: 2.6,
      strikes: 1,
      damage: 22,
      effectLife: 0.2,
      upgrades: [
        { stat: "damage", amount: 6, label: "Damage +6" },
        { stat: "cooldown", multiplier: 0.9, label: "Cooldown -10%" },
        { stat: "strikes", amount: 1, label: "Strikes +1" },
        { stat: "damage", amount: 7, label: "Damage +7" },
        { stat: "cooldown", multiplier: 0.88, label: "Cooldown -12%" },
        { stat: "strikes", amount: 1, label: "Strikes +1" },
        { stat: "damage", amount: 10, label: "Damage +10" },
      ],
    },
    arcaneStorm: {
      id: "arcaneStorm",
      name: "Tempest Codex",
      behavior: "arcaneBolt",
      isEvolution: true,
      evolvesFrom: "arcaneBolt",
      cooldown: 0.34,
      range: 980,
      volleyCount: 3,
      projectileSpeed: 920,
      projectileDamage: 28,
      projectileRadius: 18,
      projectileMaxDistance: 1500,
      pierce: 3,
      visualStyle: "storm",
    },
    celestialBlades: {
      id: "celestialBlades",
      name: "Living Margins",
      behavior: "orbitingBlade",
      isEvolution: true,
      evolvesFrom: "orbitingBlade",
      cooldown: 0,
      bladeCount: 5,
      damage: 22,
      radius: 148,
      bladeRadius: 34,
      orbitSpeed: 2.85,
      hitCooldown: 0.32,
      visualStyle: "celestial",
    },
    divineNova: {
      id: "divineNova",
      name: "Concord Dawn",
      behavior: "holyPulse",
      isEvolution: true,
      evolvesFrom: "holyPulse",
      cooldown: 3.1,
      radius: 300,
      damage: 30,
      pulseLife: 0.72,
      healOnHit: 2,
      visualStyle: "divine",
    },
    thunderCrown: {
      id: "thunderCrown",
      name: "Storm Glossary",
      behavior: "lightningMark",
      isEvolution: true,
      evolvesFrom: "lightningMark",
      cooldown: 1.75,
      strikes: 5,
      damage: 34,
      chainChance: 0.5,
      chainRadius: 240,
      effectLife: 0.38,
      visualStyle: "thunder",
    },
  },
  xpGems: {
    small: {
      value: 2,
      radius: 11,
      color: "#48a7ff",
    },
    green: {
      value: 6,
      radius: 13,
      color: "#61e37c",
    },
    red: {
      value: 12,
      radius: 15,
      color: "#ff5c5c",
    },
    magnetSpeed: 680,
    dropChances: {
      red: 0.1,
      green: 0.28,
    },
  },
  passives: {
    maxLevel: 5,
    spellbook: {
      id: "spellbook",
      cooldownMultiplier: 0.94,
      levelLabel: "Cadence -6%",
    },
    powerStone: {
      id: "powerStone",
      damageBonus: 3,
      levelLabel: "Ink power +3",
    },
    windBoots: {
      id: "windBoots",
      moveSpeedBonus: 22,
      levelLabel: "Glide speed +22",
    },
    magnetCharm: {
      id: "magnetCharm",
      magnetBonus: 34,
      levelLabel: "Shard recall +34",
    },
    ironHeart: {
      id: "ironHeart",
      maxHealthBonus: 14,
      levelLabel: "Stitched HP +14",
    },
    cloverCoin: {
      id: "cloverCoin",
      luckBonus: 0.08,
      levelLabel: "Catalog luck +8%",
    },
  },
  fallbackUpgrades: {
    heal: {
      name: "Restorative Tea",
      description: "Restore 24 HP",
      amount: 24,
    },
    coins: {
      name: "Loose Memory Coins",
      description: "Gain 25 memory coins",
      amount: 25,
    },
  },
  feedback: {
    damageNumberLife: 0.65,
    damageNumberVelocityY: -86,
    damageNumberGravity: 72,
    damageNumberHorizontalJitter: 32,
    damageNumberEnemyYOffsetRatio: 0.45,
    screenShakeDamageAmount: 6,
    screenShakeDamageDuration: 0.14,
    screenShakeChestAmount: 6,
    screenShakeChestDuration: 0.18,
    screenShakeEvolutionAmount: 10,
    screenShakeEvolutionDuration: 0.32,
    screenShakeBossAmount: 10,
    screenShakeBossDuration: 0.24,
    maxParticles: 180,
    lowHealthThreshold: 0.25,
  },
  audio: {
    music: {
      menu: "./src/assets/audio/menu-theme.mp3?v=20260629b",
      volume: 0.38,
      gameplayVolume: 0.28,
    },
  },
  menu: {
    fallbackImage: "./src/assets/menu/warrior-cat-menu.png",
    video: "./src/assets/menu/warrior-cat-menu-loop.mp4?v=20260630",
    loopCrossfade: 0,
    backgroundCrop: {
      right: 420,
      bottom: 72,
    },
  },
};
