const DEFAULT_DECORATION_TYPES = ["rock", "bone", "grassPatch", "candle", "ruin"];

export const WORLD_DEFINITIONS = [
  {
    id: "castleCourtyard",
    name: "Castle Courtyard",
    subtitle: "Stone banners · courtyard patrols",
    enemyPack: "pixelCrawler",
    tilePalette: "castleCourtyard",
    decorationTypes: ["banner", "brokenShield", "stoneColumn", "statue", "crackedStone"],
    ambientOverlayColor: "rgba(255, 214, 140, 0.08)",
    fogColor: "rgba(72, 58, 38, 0.18)",
    announcementSuffix: "Banners snap in the courtyard wind.",
    ambience: "embers",
  },
  {
    id: "summerForest",
    name: "Summer Forest",
    subtitle: "Sunlit glades · darting hunters",
    enemyPack: "tinyMonsters",
    tilePalette: "summerForest",
    decorationTypes: ["mushroom", "stump", "flowers", "bush", "roots"],
    ambientOverlayColor: "rgba(140, 200, 96, 0.08)",
    fogColor: "rgba(32, 48, 24, 0.12)",
    announcementSuffix: "Warm light spills through the canopy.",
    ambience: "pollen",
  },
  {
    id: "moonlitForest",
    name: "Moonlit Forest",
    subtitle: "Silver gloom · prowling hunters",
    enemyPack: "tinyMonsters",
    tilePalette: "moonlitForest",
    decorationTypes: ["darkTree", "blueMushroom", "fireflies", "glowingPlant", "oldLantern"],
    ambientOverlayColor: "rgba(120, 150, 220, 0.11)",
    fogColor: "rgba(28, 36, 68, 0.22)",
    announcementSuffix: "Moonlight filters through ancient trees.",
    ambience: "fireflies",
  },
  {
    id: "ancientCrypt",
    name: "Ancient Crypt",
    subtitle: "Cold vaults · rattling bones",
    enemyPack: "tinyMonsters",
    tilePalette: "ancientCrypt",
    decorationTypes: ["coffin", "skullPile", "candle", "chain", "crackedGrave"],
    ambientOverlayColor: "rgba(90, 70, 120, 0.1)",
    fogColor: "rgba(18, 14, 28, 0.24)",
    announcementSuffix: "The crypt exhales dust and dread.",
    ambience: "dust",
  },
  {
    id: "graveyard",
    name: "Moon Graveyard",
    subtitle: "Pale stones · restless dead",
    enemyPack: "cursedSpirits",
    tilePalette: "graveyard",
    decorationTypes: ["grave", "deadTree", "bonePile", "moonStone", "cursedFlower"],
    ambientOverlayColor: "rgba(140, 150, 190, 0.09)",
    fogColor: "rgba(24, 28, 42, 0.22)",
    announcementSuffix: "Grave soil splits under pale moonlight.",
    ambience: "mist",
  },
  {
    id: "cursedRuins",
    name: "Cursed Ruins",
    subtitle: "Broken stone · dark rites",
    enemyPack: "cursedSpirits",
    tilePalette: "cursedRuins",
    decorationTypes: ["redCrystal", "brokenRune", "ashPile", "cursedCandle", "ruinWall"],
    ambientOverlayColor: "rgba(180, 64, 48, 0.08)",
    fogColor: "rgba(24, 32, 18, 0.2)",
    announcementSuffix: "Cursed whispers rise from the rubble.",
    ambience: "ash",
  },
  {
    id: "royalArchive",
    name: "Royal Archive",
    subtitle: "Gilded stacks · armored sentries",
    enemyPack: "pixelCrawler",
    tilePalette: "royalArchive",
    decorationTypes: ["bookshelf", "scrollPile", "inkPot", "glowingBook", "deskDebris"],
    ambientOverlayColor: "rgba(255, 196, 96, 0.07)",
    fogColor: "rgba(42, 28, 18, 0.16)",
    announcementSuffix: "Candle smoke curls between the stacks.",
    ambience: "dust",
  },
  {
    id: "plagueVault",
    name: "Plague Vault",
    subtitle: "Sickly halls · mindless dead",
    enemyPack: "tinyMonsters",
    tilePalette: "plagueVault",
    decorationTypes: ["coffin", "skullPile", "chain", "crackedGrave", "candle"],
    ambientOverlayColor: "rgba(120, 180, 96, 0.09)",
    fogColor: "rgba(18, 32, 22, 0.24)",
    announcementSuffix: "The vault reeks of rot and rusted steel.",
    ambience: "mist",
  },
  {
    id: "frostBarrow",
    name: "Frost Barrow",
    subtitle: "Icy mounds · horned dead",
    enemyPack: "tinyMonsters",
    tilePalette: "frostBarrow",
    decorationTypes: ["bonePile", "grave", "deadTree", "moonStone", "crackedStone"],
    ambientOverlayColor: "rgba(160, 200, 230, 0.1)",
    fogColor: "rgba(28, 36, 48, 0.22)",
    announcementSuffix: "Frost cracks open the barrow graves.",
    ambience: "mist",
  },
  {
    id: "boneCrypt",
    name: "Bone Crypt",
    subtitle: "Pale vaults · clattering dead",
    enemyPack: "tinyMonsters",
    tilePalette: "boneCrypt",
    decorationTypes: ["skullPile", "coffin", "chain", "crackedGrave", "candle"],
    ambientOverlayColor: "rgba(200, 200, 210, 0.08)",
    fogColor: "rgba(24, 24, 32, 0.22)",
    announcementSuffix: "Bones scrape against cold stone.",
    ambience: "dust",
  },
  {
    id: "fallenParade",
    name: "Fallen Parade",
    subtitle: "Neon gloom · armored dead",
    enemyPack: "tinyMonsters",
    tilePalette: "fallenParade",
    decorationTypes: ["grave", "deadTree", "moonStone", "cursedFlower", "crackedStone"],
    ambientOverlayColor: "rgba(180, 96, 160, 0.09)",
    fogColor: "rgba(28, 18, 36, 0.22)",
    announcementSuffix: "A dead procession marches under pale lights.",
    ambience: "mist",
  },
  {
    id: "pixelCrawler",
    name: "Dungeon Stacks",
    subtitle: "Pixel Crawler · stone halls",
    enemyPack: "pixelCrawler",
    tilePalette: "dungeon",
    decorationTypes: DEFAULT_DECORATION_TYPES,
    ambientOverlayColor: "rgba(255, 222, 161, 0.05)",
    fogColor: "rgba(18, 20, 24, 0.14)",
    announcementSuffix: "The stacks shift to ancient stone.",
    ambience: "dust",
  },
  {
    id: "unwritten",
    name: "Unwritten Tide",
    subtitle: "Ink Procedural · the blank deep",
    enemyPack: "ink",
    tilePalette: "unwritten",
    decorationTypes: DEFAULT_DECORATION_TYPES,
    ambientOverlayColor: "rgba(120, 100, 200, 0.08)",
    fogColor: "rgba(22, 20, 36, 0.16)",
    announcementSuffix: "The Unwritten tide rises.",
    ambience: "mist",
  },
];

export function getWorldDefinition(id) {
  return WORLD_DEFINITIONS.find((world) => world.id === id) ?? WORLD_DEFINITIONS[0];
}

export function getWorldForWave(wave) {
  if (wave?.worldId) {
    return getWorldDefinition(wave.worldId);
  }

  return WORLD_DEFINITIONS[0];
}
